#ifndef STATS_HPP
#define STATS_HPP

// Personalities Stats:

#define ATTACKER_COST 5
#define ATTACKER_ATTACK 3
#define ATTACKER_DEFENSE 2
#define ATTACKER_HONOR 2

#define DEFENDER_COST 5
#define DEFNEDER_ATTACK 2
#define DEFNEDER_DEFENSE 3
#define DEFNEDER_HONOR 2

#define SHOGUN_COST 15
#define SHOGUN_ATTACK 10
#define SHOGUN_DEFENSE 5
#define SHOGUN_HONOR 8

#define CHANCELLOR_COST 15
#define CHANCELLOR_ATTACK 5
#define CHANCELLOR_DEFENSE 10
#define CHANCELLOR_HONOR 8

#define CHAMPION_COST 30
#define CHAMPION_ATTACK 20
#define CHAMPION_DEFENSE 20
#define CHAMPION_HONOR 12

// Holdings Stats:

#define PLAIN_COST 2
#define PLAIN_HARVEST 2

#define MINE_COST 5
#define MINE_HARVEST 3

#define GOLD_MINE_COST 7
#define GOLD_MINE_HARVEST 5

#define CRYSTAL_MINE_COST 12
#define CRYSTAL_MINE_HARVEST 6

#define FARMS_COST 3
#define FARMS_HARVEST 4

#define SOLO_COST 2
#define SOLO_HARVEST 2

#define STRONGHOLD_HONOR 5
#define STRONGHOLD_DEFENSE 5
#define STRONGHOLD_HARVEST 5

// Followers Stats:

#define FOOTSOLDIER_COST 0
#define FOOTSOLDIER_ATTACK_BONUS 2
#define FOOTSOLDIER_DEFENSE_BONUS 0
#define FOOTSOLDIER_MIN_HONOR 1
#define FOOTSOLDIER_EFFECT_BONUS 1
#define FOOTSOLDIER_EFFECT_COST 2

#define ARCHER_COST 0
#define ARCHER_ATTACK_BONUS 0
#define ARCHER_DEFENSE_BONUS 2
#define ARCHER_MIN_HONOR 1
#define ARCHER_EFFECT_BONUS 1
#define ARCHER_EFFECT_COST 2

#define SIEGER_COST 5
#define SIEGER_ATTACK_BONUS 3
#define SIEGER_DEFENSE_BONUS 3
#define SIEGER_MIN_HONOR 2
#define SIEGER_EFFECT_BONUS 2
#define SIEGER_EFFECT_COST 3

#define CAVALRY_COST 3
#define CAVALRY_ATTACK_BONUS 4
#define CAVALRY_DEFENSE_BONUS 2
#define CAVALRY_MIN_HONOR 3
#define CAVALRY_EFFECT_BONUS 3
#define CAVALRY_EFFECT_COST 4

#define NAVAL_COST 3
#define NAVAL_ATTACK_BONUS 2
#define NAVAL_DEFENSE_BONUS 4
#define NAVAL_MIN_HONOR 3
#define NAVAL_EFFECT_BONUS 3
#define NAVAL_EFFECT_COST 4

#define BUSHIDO_COST 8
#define BUSHIDO_ATTACK_BONUS 8
#define BUSHIDO_DEFENSE_BONUS 8
#define BUSHIDO_MIN_HONOR 6
#define BUSHIDO_EFFECT_BONUS 3
#define BUSHIDO_EFFECT_COST 8

// Items stats:

#define KATANA_COST 0
#define KATANA_ATTACK_BONUS 2
#define KATANA_DEFENSE_BONUS 0
#define KATANA_MIN_HONOR 1
#define KATANA_EFFECT_BONUS 1
#define KATANA_EFFECT_COST 2
#define KATANA_DURABILITY 3

#define SPEAR_COST 0
#define SPEAR_ATTACK_BONUS 0
#define SPEAR_DEFENSE_BONUS 2
#define SPEAR_MIN_HONOR 1
#define SPEAR_EFFECT_BONUS 1
#define SPEAR_EFFECT_COST 2
#define SPEAR_DURABILITY 3

#define BOW_COST 2
#define BOW_ATTACK_BONUS 2
#define BOW_DEFENSE_BONUS 2
#define BOW_MIN_HONOR 2
#define BOW_EFFECT_BONUS 3
#define BOW_EFFECT_COST 4
#define BOW_DURABILITY 5

#define NINJATO_COST 4
#define NINJATO_ATTACK_BONUS 3
#define NINJATO_DEFENSE_BONUS 3
#define NINJATO_MIN_HONOR 3
#define NINJATO_EFFECT_BONUS 2
#define NINJATO_EFFECT_COST 2
#define NINJATO_DURABILITY 4

#define WAKIZASHI_COST 8
#define WAKIZASHI_ATTACK_BONUS 5
#define WAKIZASHI_DEFENSE_BONUS 5
#define WAKIZASHI_MIN_HONOR 3
#define WAKIZASHI_EFFECT_BONUS 3
#define WAKIZASHI_EFFECT_COST 3
#define WAKIZASHI_DURABILITY 8

#endif